import { createApp } from "vue";
import App from "./App.vue";
import { Button, Table } from "ant-design-vue";
import router from "./router";
import 'quasar/dist/quasar.css';
import 'ant-design-vue/dist/antd.css';
import {
  Quasar,
  QLayout,
  QHeader,
  QDrawer,
  QPageContainer,
  QPage,
  QToolbar,
  QToolbarTitle,
  QBtn,
  QBtnGroup,
  QIcon,
  QList,
  QItem,
  QItemSection,
  QItemLabel,
  QMenu,
  QBtnDropdown,
  QAvatar,
  QSeparator,
  QSpace,
  QForm,
  QInput,
  QImg,
  QCheckbox,
  QTooltip,
  QBadge,
  QTabs,
  QRouteTab,
  QSelect,
  QToggle,
  QDialog,
  QCardActions,
  QSlider,
  QTab,
  QTabPanel,
  QTabPanels,
  QCard,
  QCardSection,
  QTable,
  QCircularProgress,
  QTh,
  QTr,
  QTd,
  QBreadcrumbs,
  QBreadcrumbsEl,
  QVirtualScroll,
  QExpansionItem,
  QBtnToggle,
  QChip,
  QPopupProxy,
  QColor,
} from "quasar";

const app = createApp(App);
app.use(router);
app.use(Button);
app.use(Table);
app.use(Quasar, {
  config: {},
  components: {
    QLayout,
    QHeader,
    QDrawer,
    QPageContainer,
    QPage,
    QToolbar,
    QToolbarTitle,
    QBtn,
    QBtnGroup,
    QIcon,
    QList,
    QItem,
    QItemSection,
    QItemLabel,
    QMenu,
    QBtnDropdown,
    QAvatar,
    QSeparator,
    QSpace,
    QForm,
    QInput,
    QImg,
    QCheckbox,
    QTooltip,
    QBadge,
    QTabs,
    QRouteTab,
    QSelect,
    QToggle,
    QDialog,
    QCard,
    QCardActions,
    QCardSection,
    QSlider,
    QTab,
    QTabPanel,
    QTabPanels,
    QTable,
    QCircularProgress,
    QTh,
    QTr,
    QTd,
    QBreadcrumbs,
    QBreadcrumbsEl,
    QVirtualScroll,
    QExpansionItem,
    QBtnToggle,
    QChip,
    QPopupProxy,
    QColor,
  },
});
app.mount("#app");
